version: '3'

services:
  rabbit:
      image: rabbitmq:3.5.6-management
      container_name: rabbit-pubsub
      environment:
        - RABBITMQ_DEFAULT_USER=guest
        - RABBITMQ_DEFAULT_PASS=guest
        - RABBITMQ_DEFAULT_VHOST=guest
      ports:
        - "5672:5672"
        - "15672:15672"
